### PR TITLE
[docs]: 新增评教者的身份信息

### PR DESCRIPTION
**Pull request by jzndd**
NULL

### CODE REVIEW

**Review by Jacob953 — APPROVED** [review]
Describe your changes rather than NULL!

**Review by DevRickLin — COMMENTED** [review]
Do we need a standard template for it?

**Comment by Jacob953** [comment]
> Do we need a standard template for it?

Good idea!

**Review by Jacob953 — APPROVED** [review]
LGTM, and you'd better re-format your commit information according to CONTRIBUTION.md

**Review by DevRickLin — APPROVED** [review]
LGTM

**Pull request merged**
